/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andes' at '4/29/15 3:01 PM' with Gradle 2.2.1
 *
 * @author andes, @date 4/29/15 3:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
